name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GCC
      run: choco install mingw

    - name: Compile with gcc
      run: gcc -Wall -Wextra -O2 -o chip8.exe src/chip8.c