name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: choco install make

    - name: Build
      run: make

    - name: Upload binary (optional)
      uses: actions/upload-artifact@v4
      with:
        name: chip8-binary
        path: bin/chip8.exe